using System.Globalization;
using System.Reflection;
using System.Runtime.InteropServices;
using Sagara.Core.Time;

namespace Sagara.Core.Infrastructure;

/// <summary>
/// <para>NOTE: register as a singleton. Initialize once, reuse many times.</para>
/// <para>NOTE: This was originally intended for Azure DevOps, but has now been adapted to GitHub Actions.</para>
/// <para>See: https://www.hanselman.com/blog/AddingAGitCommitHashAndAzureDevOpsBuildNumberAndBuildIDToAnASPNETWebsite.aspx</para>
/// </summary>
public class ApplicationMetadata
{
    private const string DefaultDisplayTimeZone = "America/Los_Angeles";
    private const int ShortGitHashLength = 8;

    /// <summary>
    /// Returns <see cref="RuntimeInformation.FrameworkDescription"/>.
    /// </summary>
    public string FrameworkDescription { get; }

    /// <summary>
    /// <para>Returns <see cref="RuntimeInformation.OSDescription"/> and <see cref="RuntimeInformation.OSArchitecture"/>.</para>
    /// <para>Ex: Microsoft Windows 10.0.26200, Arm64</para>
    /// </summary>
    public string OSDescription { get; }

    /// <summary>
    /// Returns the full git commit hash for this build.
    /// </summary>
    public string GitHash { get; }

    /// <summary>
    /// Returns the first <see cref="ShortGitHashLength"/> characters of <see cref="GitHash"/>.
    /// </summary>
    public string ShortGitHash { get; }

    /// <summary>
    /// Returns the git branch name from which this was built.
    /// </summary>
    public string GitBranch { get; }

    /// <summary>
    /// The GitHub Actions run number.
    /// </summary>
    public string RunNumber { get; }

    /// <summary>
    /// The UTC date and time at which this was built.
    /// </summary>
    public DateTime BuiltUtc { get; }

    /// <summary>
    /// The local date and time (defaults to America/Los_Angeles) at which this was built.
    /// </summary>
    public DateTime BuiltLocal { get; }


    /// <summary>
    /// Create a new instance, using <paramref name="applicationAssemblyType"/> to find the assembly to read
    /// the git hash from.
    /// </summary>
    /// <param name="applicationAssemblyType">Any type from the assembly to read the git hash from.</param>
    /// <param name="displayTimeZone">The IANA time zone identifier to use for the <see cref="BuiltLocal"/> property.
    /// If null, defaults to "America/Los_Angeles".</param>
    internal ApplicationMetadata(Type applicationAssemblyType, string? displayTimeZone)
    {
        Check.ThrowIfNull(applicationAssemblyType);

        FrameworkDescription = GetFrameworkDescription();
        OSDescription = GetOSDescription();

        var gitHashes = GetFullAndShortGitHashes();
        GitHash = gitHashes.FullHash;
        ShortGitHash = gitHashes.ShortHash;

        var buildInfo = GetBuildInfo();
        GitBranch = buildInfo.GitBranch;
        RunNumber = buildInfo.RunNumber;
        BuiltUtc = buildInfo.BuiltUtc;

        displayTimeZone ??= DefaultDisplayTimeZone;
        BuiltLocal = buildInfo.BuiltUtc.ToLocal(displayTimeZone).DateTime;
    }


    //
    // Private methods
    //

    /// <summary>
    /// Gets the .NET SDK version.
    /// </summary>
    private static string GetFrameworkDescription()
        => RuntimeInformation.FrameworkDescription;

    private static string GetOSDescription()
        => $"{RuntimeInformation.OSDescription}, {RuntimeInformation.OSArchitecture}";

    /// <summary>
    /// For Azure DevOps environments, gets the full and shortened git commit hashes for this build.
    /// </summary>
    private static GitHashes GetFullAndShortGitHashes()
    {
        var version = "1.0.0+LOCALBUILD"; // Dummy version for local dev.
        var assemblyInfoVerAttr = typeof(ApplicationMetadata).Assembly
            .GetCustomAttributes<AssemblyInformationalVersionAttribute>()
            .FirstOrDefault();

        if (assemblyInfoVerAttr is not null && assemblyInfoVerAttr.InformationalVersion.Length > 6)
        {
            // Hash is embedded in the version after a '+' symbol, e.g. 1.0.0+a34a913742f8845d3da5309b7b17242222d41a21
            version = assemblyInfoVerAttr.InformationalVersion;
        }

        // Full hash: take everything after the +.
        var fullHash = version.Substring(startIndex: version.IndexOf('+', StringComparison.Ordinal) + 1);

        // Short hash: take the first N characters of the git hash.
        var shortHash = fullHash[..ShortGitHashLength];

        return new GitHashes(FullHash: fullHash, ShortHash: shortHash);
    }


    private const string BUILD_INFO_FILE_PATH = ".buildinfo.json";


    /// <summary>
    /// Get the build information from the .buildinfo.json file generated by DevOps.
    /// </summary>
    private static BuildInfo GetBuildInfo()
    {
        string? runNumber = null;
        string? gitBranchName = null;
        DateTime? builtUtc = null;

        // Build number format should be yyyyMMdd.# (e.g. 20200308.1)
        if (File.Exists(BUILD_INFO_FILE_PATH))
        {
            var fileContents = File.ReadAllLines(BUILD_INFO_FILE_PATH);

            // First line is the GitHub Actions run number.
            if (fileContents.Length > 0)
            {
                runNumber = fileContents[0]?.Trim();
            }

            // Second line is the git branch name.
            if (fileContents.Length > 1)
            {
                // Unlike DevOps, this omits "refs/heads/", so we don't have to remove that part.
                gitBranchName = fileContents[1]?.Trim();
            }

            // Third line is the build date.
            if (fileContents.Length > 2)
            {
                // There is a build date in UTC, in the round trip format. Try to parse it.
                if (DateTime.TryParse(fileContents[2]?.Trim(), CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out DateTime parsedBuiltUtc))
                {
                    builtUtc = parsedBuiltUtc;
                }
            }
        }

        // Defaults in case we're in a non-Azure DevOps environment, or the .buildinfo.json file is mangled.
        if (string.IsNullOrWhiteSpace(runNumber))
        {
            runNumber = "0";
        }

        if (string.IsNullOrWhiteSpace(gitBranchName))
        {
            gitBranchName = "(none found)";
        }

        if (builtUtc is null)
        {
            builtUtc = DateTime.UtcNow;
        }

        return new BuildInfo(RunNumber: runNumber, GitBranch: gitBranchName, BuiltUtc: builtUtc.Value);
    }


    //
    // Classes
    //

    private readonly record struct GitHashes(string FullHash, string ShortHash);

    private readonly record struct BuildInfo(string RunNumber, string GitBranch, DateTime BuiltUtc);
}
